export type PregnancyMilestone = {
  week: number;
  sizeName: string;
  lengthCm: string;
  weightGrams: string;
  note: string;
};

const EARLY: PregnancyMilestone = {
  week: 0,
  sizeName: "just beginning",
  lengthCm: "too early to measure",
  weightGrams: "too early to estimate",
  note: "If you are planning a pregnancy or just starting out, rest, water, and a check-in with your clinician are a gentle first step.",
};

const MILESTONES: PregnancyMilestone[] = [
  {
    week: 1,
    sizeName: "a poppy seed",
    lengthCm: "under 0.1 cm",
    weightGrams: "under 1 g",
    note: "Early days can feel quiet. Keep meals regular and sip water through the day.",
  },
  {
    week: 2,
    sizeName: "a poppy seed",
    lengthCm: "under 0.1 cm",
    weightGrams: "under 1 g",
    note: "Gentle walks and sleep can help you feel steadier as your body begins to change.",
  },
  {
    week: 3,
    sizeName: "a sesame seed",
    lengthCm: "about 0.1 cm",
    weightGrams: "under 1 g",
    note: "Nausea or tiredness may come and go. Small snacks are often easier than large meals.",
  },
  {
    week: 4,
    sizeName: "a sesame seed",
    lengthCm: "about 0.2 cm",
    weightGrams: "under 1 g",
    note: "If something feels urgent or worrying, contact a clinician rather than waiting it out.",
  },
  {
    week: 5,
    sizeName: "an apple seed",
    lengthCm: "about 0.3 cm",
    weightGrams: "under 1 g",
    note: "Rest when you can. Light, familiar foods are a comfort for many people this week.",
  },
  {
    week: 6,
    sizeName: "a lentil",
    lengthCm: "about 0.5 cm",
    weightGrams: "about 1 g",
    note: "Short rests and loose clothing can ease early discomfort. This is general comfort advice only.",
  },
  {
    week: 7,
    sizeName: "a blueberry",
    lengthCm: "about 1 cm",
    weightGrams: "about 1 g",
    note: "Keep water nearby. If you cannot keep fluids down, seek medical care.",
  },
  {
    week: 8,
    sizeName: "a raspberry",
    lengthCm: "about 1.6 cm",
    weightGrams: "about 1 g",
    note: "A slow evening routine can support sleep as energy dips are common.",
  },
  {
    week: 9,
    sizeName: "a grape",
    lengthCm: "about 2.3 cm",
    weightGrams: "about 2 g",
    note: "Comfortable shoes and short breaks help if your day is busy.",
  },
  {
    week: 10,
    sizeName: "a strawberry",
    lengthCm: "about 3 cm",
    weightGrams: "about 4 g",
    note: "A little fresh air and stretching can lift a heavy afternoon.",
  },
  {
    week: 11,
    sizeName: "a fig",
    lengthCm: "about 4 cm",
    weightGrams: "about 7 g",
    note: "Eat what sits well. There is no single perfect plate for every day.",
  },
  {
    week: 12,
    sizeName: "a lime",
    lengthCm: "about 5 cm",
    weightGrams: "about 14 g",
    note: "Many people feel a little more themselves around now. Keep the pace kind.",
  },
  {
    week: 13,
    sizeName: "a pea pod",
    lengthCm: "about 7 cm",
    weightGrams: "about 23 g",
    note: "This is often the start of the second trimester. Stay hydrated and move gently.",
  },
  {
    week: 14,
    sizeName: "a lemon",
    lengthCm: "about 9 cm",
    weightGrams: "about 43 g",
    note: "A supportive bra and rest for your back can feel surprisingly helpful.",
  },
  {
    week: 15,
    sizeName: "an apple",
    lengthCm: "about 10 cm",
    weightGrams: "about 70 g",
    note: "If your clinician suggested prenatal visits, keep those dates nearby.",
  },
  {
    week: 16,
    sizeName: "an avocado",
    lengthCm: "about 12 cm",
    weightGrams: "about 100 g",
    note: "Side-lying rest and a pillow between the knees can ease hip strain.",
  },
  {
    week: 17,
    sizeName: "a pear",
    lengthCm: "about 13 cm",
    weightGrams: "about 140 g",
    note: "Warm (not hot) showers are a simple comfort for tight muscles.",
  },
  {
    week: 18,
    sizeName: "a bell pepper",
    lengthCm: "about 14 cm",
    weightGrams: "about 190 g",
    note: "You may notice flutters later. Every pregnancy is different.",
  },
  {
    week: 19,
    sizeName: "a mango",
    lengthCm: "about 15 cm",
    weightGrams: "about 240 g",
    note: "A short walk after a meal can feel good if your clinician has not advised otherwise.",
  },
  {
    week: 20,
    sizeName: "a banana",
    lengthCm: "about 16 cm",
    weightGrams: "about 300 g",
    note: "Halfway is a nice moment to check in with rest, support, and your next visit.",
  },
  {
    week: 21,
    sizeName: "a carrot",
    lengthCm: "about 27 cm",
    weightGrams: "about 360 g",
    note: "Length figures now often include the legs. Drink water and change positions often.",
  },
  {
    week: 22,
    sizeName: "a papaya",
    lengthCm: "about 28 cm",
    weightGrams: "about 430 g",
    note: "Swelling in the ankles can ease if you put your feet up when you can.",
  },
  {
    week: 23,
    sizeName: "a grapefruit",
    lengthCm: "about 29 cm",
    weightGrams: "about 500 g",
    note: "Sleep on your side with pillows for your belly and back if that feels better.",
  },
  {
    week: 24,
    sizeName: "an ear of corn",
    lengthCm: "about 30 cm",
    weightGrams: "about 600 g",
    note: "Notice how you feel day to day. Sudden severe symptoms need a clinician, not an app.",
  },
  {
    week: 25,
    sizeName: "a cauliflower",
    lengthCm: "about 34 cm",
    weightGrams: "about 660 g",
    note: "Heartburn is common. Smaller meals and sitting upright after eating may help.",
  },
  {
    week: 26,
    sizeName: "a bunch of spring onions",
    lengthCm: "about 35 cm",
    weightGrams: "about 760 g",
    note: "A few minutes of slow breathing can settle a busy evening.",
  },
  {
    week: 27,
    sizeName: "a head of cabbage",
    lengthCm: "about 36 cm",
    weightGrams: "about 875 g",
    note: "You are near the third trimester. Keep visits and questions written down.",
  },
  {
    week: 28,
    sizeName: "an eggplant",
    lengthCm: "about 38 cm",
    weightGrams: "about 1,000 g",
    note: "Rest your feet and loosen tight waistbands. Comfort first.",
  },
  {
    week: 29,
    sizeName: "a butternut squash",
    lengthCm: "about 39 cm",
    weightGrams: "about 1,150 g",
    note: "If kicks change a lot from your usual pattern, contact your care team.",
  },
  {
    week: 30,
    sizeName: "a coconut",
    lengthCm: "about 40 cm",
    weightGrams: "about 1,300 g",
    note: "Pack a water bottle and a snack when you leave home for long stretches.",
  },
  {
    week: 31,
    sizeName: "a pineapple",
    lengthCm: "about 41 cm",
    weightGrams: "about 1,500 g",
    note: "Short rests are still useful. You do not have to finish every task today.",
  },
  {
    week: 32,
    sizeName: "a squash",
    lengthCm: "about 42 cm",
    weightGrams: "about 1,700 g",
    note: "Practice getting in and out of bed slowly to spare your back.",
  },
  {
    week: 33,
    sizeName: "a pineapple",
    lengthCm: "about 44 cm",
    weightGrams: "about 1,900 g",
    note: "Keep the bedroom cool and dark if sleep is broken.",
  },
  {
    week: 34,
    sizeName: "a cantaloupe",
    lengthCm: "about 45 cm",
    weightGrams: "about 2,150 g",
    note: "Gather questions for your next visit while they are fresh.",
  },
  {
    week: 35,
    sizeName: "a honeydew melon",
    lengthCm: "about 46 cm",
    weightGrams: "about 2,400 g",
    note: "Braxton-like tightness can happen. Painful, regular tightening needs clinical advice.",
  },
  {
    week: 36,
    sizeName: "a romaine lettuce",
    lengthCm: "about 47 cm",
    weightGrams: "about 2,600 g",
    note: "Many clinics see you more often now. Keep your visit date updated here.",
  },
  {
    week: 37,
    sizeName: "a bunch of Swiss chard",
    lengthCm: "about 48 cm",
    weightGrams: "about 2,900 g",
    note: "Early term can still mean waiting. Rest, hydrate, and follow your clinician’s plan.",
  },
  {
    week: 38,
    sizeName: "a leek",
    lengthCm: "about 49 cm",
    weightGrams: "about 3,100 g",
    note: "Have your hospital or birth-place bag in one place so you are not rushing.",
  },
  {
    week: 39,
    sizeName: "a mini watermelon",
    lengthCm: "about 50 cm",
    weightGrams: "about 3,300 g",
    note: "Full term is near. Call your care team for bleeding, fluid loss, or severe pain.",
  },
  {
    week: 40,
    sizeName: "a small pumpkin",
    lengthCm: "about 51 cm",
    weightGrams: "about 3,400 g",
    note: "Due dates are estimates. Your clinician decides what follow-up you need after this week.",
  },
];

export function getPregnancyMilestone(week: number): PregnancyMilestone {
  if (week <= 0) return EARLY;
  if (week >= 40) return MILESTONES[39];
  return MILESTONES[week - 1] ?? EARLY;
}
